export function get_config() {
  const config = {
    version: "26.01.04",
    default_filename: "mysprites",
    sprite_x: 24,
    sprite_y: 21,
    sprite_defaults: {
      background_color: 11,      // Light gray (pen 0)
      multicolor_1: 8,            // Orange (pen 2)
      multicolor_2: 6,            // Blue (pen 3)
      individual_color: 1,        // White (pen 1)
      pen: 1,                     // Default drawing pen
      animation_fps: 10,
      animation_mode: "restart",
    },
    zoom_limits: {
      editor: { min: 10, max: 26 },
      preview: { min: 4, max: 16 },
      list: { min: 4, max: 16 },
      animation: { min: 4, max: 16 },
    },
    color_names:["black", "white", "red", "cyan", "purple","green","blue","yellow","orange","brown","pink","dark grey","grey","light green","light blue","light grey"],
    palettes: {
      colodore: {
        name: "Colodore",
        values: [
          "#000000",
          "#ffffff",
          "#813338",
          "#75cec8",
          "#8e3c97",
          "#56ac4d",
          "#2e2c9b",
          "#edf171",
          "#8e5029",
          "#553800",
          "#c46c71",
          "#4a4a4a",
          "#7b7b7b",
          "#a9ff9f",
          "#706deb",
          "#b2b2b2",
        ],
      },
      palette: {
        name: "PALette",
        values: [
          "#000000",
          "#ffffff",
          "#af2a29",
          "#6ed8cc",
          "#b03fb6",
          "#4ac64a",
          "#3739c4",
          "#e4ed4e",
          "#b6591c",
          "#683808",
          "#ea746c",
          "#4d4d4d",
          "#848484",
          "#a6fa9e",
          "#707ce6",
          "#b6b6b5",
        ],
      },
      pepto: {
        name: "Pepto",
        values: [
          "#000000",
          "#ffffff",
          "#67372d",
          "#73a3b1",
          "#6e3e83",
          "#5b8d48",
          "#362976",
          "#b7c576",
          "#6c4f2a",
          "#423908",
          "#98675b",
          "#444444",
          "#6c6c6c",
          "#9dd28a",
          "#6d5fb0",
          "#959595",
        ],
      },
      custom: {
        name: "Custom",
        values: [
          "#000000",
          "#ffffff",
          "#813338",
          "#75cec8",
          "#8e3c97",
          "#56ac4d",
          "#2e2c9b",
          "#edf171",
          "#8e5029",
          "#553800",
          "#c46c71",
          "#4a4a4a",
          "#7b7b7b",
          "#a9ff9f",
          "#706deb",
          "#b2b2b2",
        ],
      },
    },
    selected_palette: "pepto",
    window_tools: {
      top: 50,
      left: 20,
      autoOpen: true,
      closeable: false,
    },
    window_editor: {
      top: 50,
      left: 210,
      zoom: 18,
      grid: true,
      autoOpen: true,
      closeable: false,
    },
    window_preview: {
      top: 50,
      left: 700,
      zoom: 6,
      autoOpen: true,
      closeable: false,
      isOpen: true,
    },
    window_list: {
      top: 280,
      left: 700,
      width: 440,
      height: 200,
      zoom: 4,
      autoOpen: true,
      closeable: false,
    },
    window_palette: {
      top: 50,
      left: 110,
      zoom: 1,
      autoOpen: true,
      closeable: false,
    },
    window_snapshot: {
      top: 400,
      left: 110,
      width: 440,
      height: 200,
      zoom: 1,
      autoOpen: false,
      closeable: true,
      isOpen: false,
    },
    window_animation: {
      top: 280,
      left: 210,
      width: 440,
      zoom: 6,
      autoOpen: false,
      closeable: true,
      isOpen: false,
    },
    window_playfield: {
      top: 100,
      left: 800,
      zoom: 1,
      grid: false,
      autoOpen: false,
      closeable: true,
      isOpen: false,
    },
  };

  return config;
}
